# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Accenture' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'happypathdesafioaccenture' do
    @driver.get('http://sampleapp.tricentis.com/101/app.php')
    @driver.manage.resize_to(1382, 744)
    @driver.find_element(:id, 'make').click
    dropdown = @driver.find_element(:id, 'make')
    dropdown.find_element(:xpath, "//option[. = 'Audi']").click
    @driver.find_element(:id, 'make').click
    @driver.find_element(:id, 'engineperformance').click
    @driver.find_element(:id, 'engineperformance').send_keys('1000')
    @driver.find_element(:css, '#opendateofmanufacturecalender > .fa').click
    @driver.find_element(:link_text, '1').click
    @driver.find_element(:id, 'numberofseats').click
    dropdown = @driver.find_element(:id, 'numberofseats')
    dropdown.find_element(:xpath, "//option[. = '6']").click
    @driver.find_element(:id, 'numberofseats').click
    @driver.find_element(:id, 'fuel').click
    dropdown = @driver.find_element(:id, 'fuel')
    dropdown.find_element(:xpath, "//option[. = 'Electric Power']").click
    @driver.find_element(:id, 'fuel').click
    @driver.find_element(:id, 'listprice').click
    @driver.find_element(:id, 'listprice').click
    @driver.find_element(:id, 'listprice').send_keys('10000')
    @driver.find_element(:id, 'licenseplatenumber').click
    @driver.find_element(:id, 'licenseplatenumber').send_keys('fgtr3000')
    @driver.find_element(:id, 'annualmileage').click
    @driver.find_element(:id, 'annualmileage').send_keys('10000')
    @driver.find_element(:id, 'nextenterinsurantdata').click
    @driver.find_element(:id, 'firstname').click
    @driver.find_element(:id, 'firstname').send_keys('ghost')
    @driver.find_element(:id, 'lastname').click
    @driver.find_element(:id, 'lastname').send_keys('writer')
    @driver.find_element(:css, '#opendateofbirthcalender > .fa').click
    @driver.find_element(:css, '.ui-datepicker-next').click
    @driver.find_element(:css, '.ui-datepicker-next').click
    @driver.find_element(:link_text, '13').click
    @driver.find_element(:id, 'birthdate').click
    @driver.find_element(:id, 'birthdate').send_keys('08/13/1969')
    @driver.find_element(:css, '.group:nth-child(2) > .ideal-radiocheck-label:nth-child(1) > .ideal-radio').click
    @driver.find_element(:id, 'streetaddress').click
    @driver.find_element(:id, 'streetaddress').send_keys('rua bla bla')
    @driver.find_element(:id, 'country').click
    dropdown = @driver.find_element(:id, 'country')
    dropdown.find_element(:xpath, "//option[. = 'Brazil']").click
    @driver.find_element(:id, 'country').click
    @driver.find_element(:id, 'zipcode').click
    @driver.find_element(:id, 'zipcode').send_keys('20000')
    @driver.find_element(:id, 'city').click
    @driver.find_element(:id, 'city').send_keys('rio de janeiro')
    @driver.find_element(:id, 'occupation').click
    dropdown = @driver.find_element(:id, 'occupation')
    dropdown.find_element(:xpath, "//option[. = 'Employee']").click
    @driver.find_element(:id, 'occupation').click
    @driver.find_element(:css, '.ideal-radiocheck-label:nth-child(5) > .ideal-check').click
    @driver.find_element(:id, 'nextenterproductdata').click
    @driver.find_element(:css, '#openstartdatecalender > .fa').click
    @driver.find_element(:css, '.ui-datepicker-next').click
    @driver.find_element(:css, '.ui-datepicker-next').click
    @driver.find_element(:link_text, '7').click
    @driver.find_element(:id, 'insurancesum').click
    dropdown = @driver.find_element(:id, 'insurancesum')
    dropdown.find_element(:xpath, "//option[. = '3.000.000,00']").click
    @driver.find_element(:id, 'insurancesum').click
    @driver.find_element(:id, 'meritrating').click
    dropdown = @driver.find_element(:id, 'meritrating')
    dropdown.find_element(:xpath, "//option[. = 'Bonus 8']").click
    @driver.find_element(:id, 'meritrating').click
    @driver.find_element(:id, 'damageinsurance').click
    dropdown = @driver.find_element(:id, 'damageinsurance')
    dropdown.find_element(:xpath, "//option[. = 'No Coverage']").click
    @driver.find_element(:id, 'damageinsurance').click
    @driver.find_element(:css, '.field:nth-child(5) .ideal-radiocheck-label:nth-child(2) > .ideal-check').click
    @driver.find_element(:id, 'courtesycar').click
    dropdown = @driver.find_element(:id, 'courtesycar')
    dropdown.find_element(:xpath, "//option[. = 'Yes']").click
    @driver.find_element(:id, 'courtesycar').click
    @driver.find_element(:id, 'nextselectpriceoption').click
    @driver.find_element(:css, '.choosePrice:nth-child(4) > .ideal-radio').click
    @driver.find_element(:id, 'nextsendquote').click
    @driver.find_element(:id, 'email').click
    @driver.find_element(:id, 'email').send_keys('andremaia2@yahoo.com.br')
    @driver.find_element(:id, 'phone').send_keys('21982537912')
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').send_keys('ghostW')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('Aa008980')
    @driver.find_element(:id, 'confirmpassword').click
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('Qwerty90')
    @driver.find_element(:id, 'confirmpassword').click
    @driver.find_element(:id, 'confirmpassword').send_keys('Qwerty90')
    @driver.find_element(:id, 'sendemail').click
    @driver.find_element(:css, '.confirm').click
  end
  it 'testenegativodesafioaccenture' do
    @driver.get('http://sampleapp.tricentis.com/101/app.php')
    @driver.manage.resize_to(1382, 744)
    @driver.find_element(:id, 'make').click
    dropdown = @driver.find_element(:id, 'make')
    dropdown.find_element(:xpath, "//option[. = 'Audi']").click
    @driver.find_element(:id, 'make').click
    @driver.find_element(:id, 'engineperformance').click
    @driver.find_element(:id, 'engineperformance').send_keys('10000')
    @driver.find_element(:css, '#opendateofmanufacturecalender > .fa').click
    @driver.find_element(:link_text, '1').click
    @driver.find_element(:id, 'numberofseats').click
    dropdown = @driver.find_element(:id, 'numberofseats')
    dropdown.find_element(:xpath, "//option[. = '6']").click
    @driver.find_element(:id, 'numberofseats').click
    @driver.find_element(:id, 'fuel').click
    dropdown = @driver.find_element(:id, 'fuel')
    dropdown.find_element(:xpath, "//option[. = 'Electric Power']").click
    @driver.find_element(:id, 'fuel').click
    @driver.find_element(:id, 'listprice').click
    @driver.find_element(:id, 'listprice').click
    @driver.find_element(:id, 'listprice').send_keys('1000')
    @driver.find_element(:id, 'licenseplatenumber').click
    @driver.find_element(:id, 'licenseplatenumber').send_keys('fgtr3000')
    @driver.find_element(:id, 'annualmileage').click
    @driver.find_element(:id, 'annualmileage').send_keys('10000')
    @driver.find_element(:id, 'nextenterinsurantdata').click
    @driver.find_element(:id, 'firstname').click
    @driver.find_element(:id, 'firstname').send_keys('ghost')
    @driver.find_element(:id, 'lastname').click
    @driver.find_element(:id, 'lastname').send_keys('writer')
    @driver.find_element(:css, '#opendateofbirthcalender > .fa').click
    @driver.find_element(:css, '.ui-datepicker-next').click
    @driver.find_element(:css, '.ui-datepicker-next').click
    @driver.find_element(:link_text, '13').click
    @driver.find_element(:id, 'birthdate').click
    @driver.find_element(:id, 'birthdate').send_keys('08/13/1969')
    @driver.find_element(:css, '.group:nth-child(2) > .ideal-radiocheck-label:nth-child(1) > .ideal-radio').click
    @driver.find_element(:id, 'streetaddress').click
    @driver.find_element(:id, 'streetaddress').send_keys('rua bla bla')
    @driver.find_element(:id, 'country').click
    dropdown = @driver.find_element(:id, 'country')
    dropdown.find_element(:xpath, "//option[. = 'Brazil']").click
    @driver.find_element(:id, 'country').click
    @driver.find_element(:id, 'zipcode').click
    @driver.find_element(:id, 'zipcode').send_keys('20000')
    @driver.find_element(:id, 'city').click
    @driver.find_element(:id, 'city').send_keys('rio de janeiro')
    @driver.find_element(:id, 'occupation').click
    dropdown = @driver.find_element(:id, 'occupation')
    dropdown.find_element(:xpath, "//option[. = 'Employee']").click
    @driver.find_element(:id, 'occupation').click
    @driver.find_element(:css, '.ideal-radiocheck-label:nth-child(5) > .ideal-check').click
    @driver.find_element(:id, 'nextenterproductdata').click
    @driver.find_element(:css, '#openstartdatecalender > .fa').click
    @driver.find_element(:css, '.ui-datepicker-next').click
    @driver.find_element(:css, '.ui-datepicker-next').click
    @driver.find_element(:link_text, '7').click
    @driver.find_element(:id, 'insurancesum').click
    dropdown = @driver.find_element(:id, 'insurancesum')
    dropdown.find_element(:xpath, "//option[. = '3.000.000,00']").click
    @driver.find_element(:id, 'insurancesum').click
    @driver.find_element(:id, 'meritrating').click
    dropdown = @driver.find_element(:id, 'meritrating')
    dropdown.find_element(:xpath, "//option[. = 'Bonus 8']").click
    @driver.find_element(:id, 'meritrating').click
    @driver.find_element(:id, 'damageinsurance').click
    dropdown = @driver.find_element(:id, 'damageinsurance')
    dropdown.find_element(:xpath, "//option[. = 'No Coverage']").click
    @driver.find_element(:id, 'damageinsurance').click
    @driver.find_element(:css, '.field:nth-child(5) .ideal-radiocheck-label:nth-child(2) > .ideal-check').click
    @driver.find_element(:id, 'courtesycar').click
    dropdown = @driver.find_element(:id, 'courtesycar')
    dropdown.find_element(:xpath, "//option[. = 'Yes']").click
    @driver.find_element(:id, 'courtesycar').click
    @driver.find_element(:id, 'nextselectpriceoption').click
    @driver.find_element(:css, '.choosePrice:nth-child(4) > .ideal-radio').click
    @driver.find_element(:id, 'nextsendquote').click
    @driver.find_element(:id, 'email').click
    @driver.find_element(:id, 'email').send_keys('andremaia2@yahoo.com.br')
    @driver.find_element(:id, 'phone').send_keys('21982537912')
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').send_keys('ghostW')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('Aa008980')
    @driver.find_element(:id, 'confirmpassword').click
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('Qwerty90')
    @driver.find_element(:id, 'confirmpassword').click
    @driver.find_element(:id, 'confirmpassword').send_keys('Qwerty90')
    @driver.find_element(:id, 'sendemail').click
    @driver.find_element(:css, '.confirm').click
  end
end
