// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AccentureTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void happypathdesafioaccenture() {
    driver.Navigate().GoToUrl("http://sampleapp.tricentis.com/101/app.php");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    driver.FindElement(By.Id("make")).Click();
    {
      var dropdown = driver.FindElement(By.Id("make"));
      dropdown.FindElement(By.XPath("//option[. = 'Audi']")).Click();
    }
    driver.FindElement(By.Id("make")).Click();
    driver.FindElement(By.Id("engineperformance")).Click();
    driver.FindElement(By.Id("engineperformance")).SendKeys("1000");
    driver.FindElement(By.CssSelector("#opendateofmanufacturecalender > .fa")).Click();
    driver.FindElement(By.LinkText("1")).Click();
    driver.FindElement(By.Id("numberofseats")).Click();
    {
      var dropdown = driver.FindElement(By.Id("numberofseats"));
      dropdown.FindElement(By.XPath("//option[. = '6']")).Click();
    }
    driver.FindElement(By.Id("numberofseats")).Click();
    driver.FindElement(By.Id("fuel")).Click();
    {
      var dropdown = driver.FindElement(By.Id("fuel"));
      dropdown.FindElement(By.XPath("//option[. = 'Electric Power']")).Click();
    }
    driver.FindElement(By.Id("fuel")).Click();
    driver.FindElement(By.Id("listprice")).Click();
    driver.FindElement(By.Id("listprice")).Click();
    driver.FindElement(By.Id("listprice")).SendKeys("10000");
    driver.FindElement(By.Id("licenseplatenumber")).Click();
    driver.FindElement(By.Id("licenseplatenumber")).SendKeys("fgtr3000");
    driver.FindElement(By.Id("annualmileage")).Click();
    driver.FindElement(By.Id("annualmileage")).SendKeys("10000");
    driver.FindElement(By.Id("nextenterinsurantdata")).Click();
    driver.FindElement(By.Id("firstname")).Click();
    driver.FindElement(By.Id("firstname")).SendKeys("ghost");
    driver.FindElement(By.Id("lastname")).Click();
    driver.FindElement(By.Id("lastname")).SendKeys("writer");
    driver.FindElement(By.CssSelector("#opendateofbirthcalender > .fa")).Click();
    driver.FindElement(By.CssSelector(".ui-datepicker-next")).Click();
    driver.FindElement(By.CssSelector(".ui-datepicker-next")).Click();
    driver.FindElement(By.LinkText("13")).Click();
    driver.FindElement(By.Id("birthdate")).Click();
    driver.FindElement(By.Id("birthdate")).SendKeys("08/13/1969");
    driver.FindElement(By.CssSelector(".group:nth-child(2) > .ideal-radiocheck-label:nth-child(1) > .ideal-radio")).Click();
    driver.FindElement(By.Id("streetaddress")).Click();
    driver.FindElement(By.Id("streetaddress")).SendKeys("rua bla bla");
    driver.FindElement(By.Id("country")).Click();
    {
      var dropdown = driver.FindElement(By.Id("country"));
      dropdown.FindElement(By.XPath("//option[. = 'Brazil']")).Click();
    }
    driver.FindElement(By.Id("country")).Click();
    driver.FindElement(By.Id("zipcode")).Click();
    driver.FindElement(By.Id("zipcode")).SendKeys("20000");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("rio de janeiro");
    driver.FindElement(By.Id("occupation")).Click();
    {
      var dropdown = driver.FindElement(By.Id("occupation"));
      dropdown.FindElement(By.XPath("//option[. = 'Employee']")).Click();
    }
    driver.FindElement(By.Id("occupation")).Click();
    driver.FindElement(By.CssSelector(".ideal-radiocheck-label:nth-child(5) > .ideal-check")).Click();
    driver.FindElement(By.Id("nextenterproductdata")).Click();
    driver.FindElement(By.CssSelector("#openstartdatecalender > .fa")).Click();
    driver.FindElement(By.CssSelector(".ui-datepicker-next")).Click();
    driver.FindElement(By.CssSelector(".ui-datepicker-next")).Click();
    driver.FindElement(By.LinkText("7")).Click();
    driver.FindElement(By.Id("insurancesum")).Click();
    {
      var dropdown = driver.FindElement(By.Id("insurancesum"));
      dropdown.FindElement(By.XPath("//option[. = '3.000.000,00']")).Click();
    }
    driver.FindElement(By.Id("insurancesum")).Click();
    driver.FindElement(By.Id("meritrating")).Click();
    {
      var dropdown = driver.FindElement(By.Id("meritrating"));
      dropdown.FindElement(By.XPath("//option[. = 'Bonus 8']")).Click();
    }
    driver.FindElement(By.Id("meritrating")).Click();
    driver.FindElement(By.Id("damageinsurance")).Click();
    {
      var dropdown = driver.FindElement(By.Id("damageinsurance"));
      dropdown.FindElement(By.XPath("//option[. = 'No Coverage']")).Click();
    }
    driver.FindElement(By.Id("damageinsurance")).Click();
    driver.FindElement(By.CssSelector(".field:nth-child(5) .ideal-radiocheck-label:nth-child(2) > .ideal-check")).Click();
    driver.FindElement(By.Id("courtesycar")).Click();
    {
      var dropdown = driver.FindElement(By.Id("courtesycar"));
      dropdown.FindElement(By.XPath("//option[. = 'Yes']")).Click();
    }
    driver.FindElement(By.Id("courtesycar")).Click();
    driver.FindElement(By.Id("nextselectpriceoption")).Click();
    driver.FindElement(By.CssSelector(".choosePrice:nth-child(4) > .ideal-radio")).Click();
    driver.FindElement(By.Id("nextsendquote")).Click();
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("andremaia2@yahoo.com.br");
    driver.FindElement(By.Id("phone")).SendKeys("21982537912");
    driver.FindElement(By.Id("username")).Click();
    driver.FindElement(By.Id("username")).Click();
    driver.FindElement(By.Id("username")).SendKeys("ghostW");
    driver.FindElement(By.Id("password")).Click();
    driver.FindElement(By.Id("password")).SendKeys("Aa008980");
    driver.FindElement(By.Id("confirmpassword")).Click();
    driver.FindElement(By.Id("password")).Click();
    driver.FindElement(By.Id("password")).SendKeys("Qwerty90");
    driver.FindElement(By.Id("confirmpassword")).Click();
    driver.FindElement(By.Id("confirmpassword")).SendKeys("Qwerty90");
    driver.FindElement(By.Id("sendemail")).Click();
    driver.FindElement(By.CssSelector(".confirm")).Click();
  }
  [Test]
  public void testenegativodesafioaccenture() {
    driver.Navigate().GoToUrl("http://sampleapp.tricentis.com/101/app.php");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    driver.FindElement(By.Id("make")).Click();
    {
      var dropdown = driver.FindElement(By.Id("make"));
      dropdown.FindElement(By.XPath("//option[. = 'Audi']")).Click();
    }
    driver.FindElement(By.Id("make")).Click();
    driver.FindElement(By.Id("engineperformance")).Click();
    driver.FindElement(By.Id("engineperformance")).SendKeys("10000");
    driver.FindElement(By.CssSelector("#opendateofmanufacturecalender > .fa")).Click();
    driver.FindElement(By.LinkText("1")).Click();
    driver.FindElement(By.Id("numberofseats")).Click();
    {
      var dropdown = driver.FindElement(By.Id("numberofseats"));
      dropdown.FindElement(By.XPath("//option[. = '6']")).Click();
    }
    driver.FindElement(By.Id("numberofseats")).Click();
    driver.FindElement(By.Id("fuel")).Click();
    {
      var dropdown = driver.FindElement(By.Id("fuel"));
      dropdown.FindElement(By.XPath("//option[. = 'Electric Power']")).Click();
    }
    driver.FindElement(By.Id("fuel")).Click();
    driver.FindElement(By.Id("listprice")).Click();
    driver.FindElement(By.Id("listprice")).Click();
    driver.FindElement(By.Id("listprice")).SendKeys("1000");
    driver.FindElement(By.Id("licenseplatenumber")).Click();
    driver.FindElement(By.Id("licenseplatenumber")).SendKeys("fgtr3000");
    driver.FindElement(By.Id("annualmileage")).Click();
    driver.FindElement(By.Id("annualmileage")).SendKeys("10000");
    driver.FindElement(By.Id("nextenterinsurantdata")).Click();
    driver.FindElement(By.Id("firstname")).Click();
    driver.FindElement(By.Id("firstname")).SendKeys("ghost");
    driver.FindElement(By.Id("lastname")).Click();
    driver.FindElement(By.Id("lastname")).SendKeys("writer");
    driver.FindElement(By.CssSelector("#opendateofbirthcalender > .fa")).Click();
    driver.FindElement(By.CssSelector(".ui-datepicker-next")).Click();
    driver.FindElement(By.CssSelector(".ui-datepicker-next")).Click();
    driver.FindElement(By.LinkText("13")).Click();
    driver.FindElement(By.Id("birthdate")).Click();
    driver.FindElement(By.Id("birthdate")).SendKeys("08/13/1969");
    driver.FindElement(By.CssSelector(".group:nth-child(2) > .ideal-radiocheck-label:nth-child(1) > .ideal-radio")).Click();
    driver.FindElement(By.Id("streetaddress")).Click();
    driver.FindElement(By.Id("streetaddress")).SendKeys("rua bla bla");
    driver.FindElement(By.Id("country")).Click();
    {
      var dropdown = driver.FindElement(By.Id("country"));
      dropdown.FindElement(By.XPath("//option[. = 'Brazil']")).Click();
    }
    driver.FindElement(By.Id("country")).Click();
    driver.FindElement(By.Id("zipcode")).Click();
    driver.FindElement(By.Id("zipcode")).SendKeys("20000");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("rio de janeiro");
    driver.FindElement(By.Id("occupation")).Click();
    {
      var dropdown = driver.FindElement(By.Id("occupation"));
      dropdown.FindElement(By.XPath("//option[. = 'Employee']")).Click();
    }
    driver.FindElement(By.Id("occupation")).Click();
    driver.FindElement(By.CssSelector(".ideal-radiocheck-label:nth-child(5) > .ideal-check")).Click();
    driver.FindElement(By.Id("nextenterproductdata")).Click();
    driver.FindElement(By.CssSelector("#openstartdatecalender > .fa")).Click();
    driver.FindElement(By.CssSelector(".ui-datepicker-next")).Click();
    driver.FindElement(By.CssSelector(".ui-datepicker-next")).Click();
    driver.FindElement(By.LinkText("7")).Click();
    driver.FindElement(By.Id("insurancesum")).Click();
    {
      var dropdown = driver.FindElement(By.Id("insurancesum"));
      dropdown.FindElement(By.XPath("//option[. = '3.000.000,00']")).Click();
    }
    driver.FindElement(By.Id("insurancesum")).Click();
    driver.FindElement(By.Id("meritrating")).Click();
    {
      var dropdown = driver.FindElement(By.Id("meritrating"));
      dropdown.FindElement(By.XPath("//option[. = 'Bonus 8']")).Click();
    }
    driver.FindElement(By.Id("meritrating")).Click();
    driver.FindElement(By.Id("damageinsurance")).Click();
    {
      var dropdown = driver.FindElement(By.Id("damageinsurance"));
      dropdown.FindElement(By.XPath("//option[. = 'No Coverage']")).Click();
    }
    driver.FindElement(By.Id("damageinsurance")).Click();
    driver.FindElement(By.CssSelector(".field:nth-child(5) .ideal-radiocheck-label:nth-child(2) > .ideal-check")).Click();
    driver.FindElement(By.Id("courtesycar")).Click();
    {
      var dropdown = driver.FindElement(By.Id("courtesycar"));
      dropdown.FindElement(By.XPath("//option[. = 'Yes']")).Click();
    }
    driver.FindElement(By.Id("courtesycar")).Click();
    driver.FindElement(By.Id("nextselectpriceoption")).Click();
    driver.FindElement(By.CssSelector(".choosePrice:nth-child(4) > .ideal-radio")).Click();
    driver.FindElement(By.Id("nextsendquote")).Click();
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("andremaia2@yahoo.com.br");
    driver.FindElement(By.Id("phone")).SendKeys("21982537912");
    driver.FindElement(By.Id("username")).Click();
    driver.FindElement(By.Id("username")).Click();
    driver.FindElement(By.Id("username")).SendKeys("ghostW");
    driver.FindElement(By.Id("password")).Click();
    driver.FindElement(By.Id("password")).SendKeys("Aa008980");
    driver.FindElement(By.Id("confirmpassword")).Click();
    driver.FindElement(By.Id("password")).Click();
    driver.FindElement(By.Id("password")).SendKeys("Qwerty90");
    driver.FindElement(By.Id("confirmpassword")).Click();
    driver.FindElement(By.Id("confirmpassword")).SendKeys("Qwerty90");
    driver.FindElement(By.Id("sendemail")).Click();
    driver.FindElement(By.CssSelector(".confirm")).Click();
  }
}
