// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HappypathdesafioaccentureTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void happypathdesafioaccenture() {
    driver.get("http://sampleapp.tricentis.com/101/app.php");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.id("make")).click();
    {
      WebElement dropdown = driver.findElement(By.id("make"));
      dropdown.findElement(By.xpath("//option[. = 'Audi']")).click();
    }
    driver.findElement(By.id("make")).click();
    driver.findElement(By.id("engineperformance")).click();
    driver.findElement(By.id("engineperformance")).sendKeys("1000");
    driver.findElement(By.cssSelector("#opendateofmanufacturecalender > .fa")).click();
    driver.findElement(By.linkText("1")).click();
    driver.findElement(By.id("numberofseats")).click();
    {
      WebElement dropdown = driver.findElement(By.id("numberofseats"));
      dropdown.findElement(By.xpath("//option[. = '6']")).click();
    }
    driver.findElement(By.id("numberofseats")).click();
    driver.findElement(By.id("fuel")).click();
    {
      WebElement dropdown = driver.findElement(By.id("fuel"));
      dropdown.findElement(By.xpath("//option[. = 'Electric Power']")).click();
    }
    driver.findElement(By.id("fuel")).click();
    driver.findElement(By.id("listprice")).click();
    driver.findElement(By.id("listprice")).click();
    driver.findElement(By.id("listprice")).sendKeys("10000");
    driver.findElement(By.id("licenseplatenumber")).click();
    driver.findElement(By.id("licenseplatenumber")).sendKeys("fgtr3000");
    driver.findElement(By.id("annualmileage")).click();
    driver.findElement(By.id("annualmileage")).sendKeys("10000");
    driver.findElement(By.id("nextenterinsurantdata")).click();
    driver.findElement(By.id("firstname")).click();
    driver.findElement(By.id("firstname")).sendKeys("ghost");
    driver.findElement(By.id("lastname")).click();
    driver.findElement(By.id("lastname")).sendKeys("writer");
    driver.findElement(By.cssSelector("#opendateofbirthcalender > .fa")).click();
    driver.findElement(By.cssSelector(".ui-datepicker-next")).click();
    driver.findElement(By.cssSelector(".ui-datepicker-next")).click();
    driver.findElement(By.linkText("13")).click();
    driver.findElement(By.id("birthdate")).click();
    driver.findElement(By.id("birthdate")).sendKeys("08/13/1969");
    driver.findElement(By.cssSelector(".group:nth-child(2) > .ideal-radiocheck-label:nth-child(1) > .ideal-radio")).click();
    driver.findElement(By.id("streetaddress")).click();
    driver.findElement(By.id("streetaddress")).sendKeys("rua bla bla");
    driver.findElement(By.id("country")).click();
    {
      WebElement dropdown = driver.findElement(By.id("country"));
      dropdown.findElement(By.xpath("//option[. = 'Brazil']")).click();
    }
    driver.findElement(By.id("country")).click();
    driver.findElement(By.id("zipcode")).click();
    driver.findElement(By.id("zipcode")).sendKeys("20000");
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("city")).sendKeys("rio de janeiro");
    driver.findElement(By.id("occupation")).click();
    {
      WebElement dropdown = driver.findElement(By.id("occupation"));
      dropdown.findElement(By.xpath("//option[. = 'Employee']")).click();
    }
    driver.findElement(By.id("occupation")).click();
    driver.findElement(By.cssSelector(".ideal-radiocheck-label:nth-child(5) > .ideal-check")).click();
    driver.findElement(By.id("nextenterproductdata")).click();
    driver.findElement(By.cssSelector("#openstartdatecalender > .fa")).click();
    driver.findElement(By.cssSelector(".ui-datepicker-next")).click();
    driver.findElement(By.cssSelector(".ui-datepicker-next")).click();
    driver.findElement(By.linkText("7")).click();
    driver.findElement(By.id("insurancesum")).click();
    {
      WebElement dropdown = driver.findElement(By.id("insurancesum"));
      dropdown.findElement(By.xpath("//option[. = '3.000.000,00']")).click();
    }
    driver.findElement(By.id("insurancesum")).click();
    driver.findElement(By.id("meritrating")).click();
    {
      WebElement dropdown = driver.findElement(By.id("meritrating"));
      dropdown.findElement(By.xpath("//option[. = 'Bonus 8']")).click();
    }
    driver.findElement(By.id("meritrating")).click();
    driver.findElement(By.id("damageinsurance")).click();
    {
      WebElement dropdown = driver.findElement(By.id("damageinsurance"));
      dropdown.findElement(By.xpath("//option[. = 'No Coverage']")).click();
    }
    driver.findElement(By.id("damageinsurance")).click();
    driver.findElement(By.cssSelector(".field:nth-child(5) .ideal-radiocheck-label:nth-child(2) > .ideal-check")).click();
    driver.findElement(By.id("courtesycar")).click();
    {
      WebElement dropdown = driver.findElement(By.id("courtesycar"));
      dropdown.findElement(By.xpath("//option[. = 'Yes']")).click();
    }
    driver.findElement(By.id("courtesycar")).click();
    driver.findElement(By.id("nextselectpriceoption")).click();
    driver.findElement(By.cssSelector(".choosePrice:nth-child(4) > .ideal-radio")).click();
    driver.findElement(By.id("nextsendquote")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("andremaia2@yahoo.com.br");
    driver.findElement(By.id("phone")).sendKeys("21982537912");
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("ghostW");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Aa008980");
    driver.findElement(By.id("confirmpassword")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Qwerty90");
    driver.findElement(By.id("confirmpassword")).click();
    driver.findElement(By.id("confirmpassword")).sendKeys("Qwerty90");
    driver.findElement(By.id("sendemail")).click();
    driver.findElement(By.cssSelector(".confirm")).click();
  }
}
